:Note: Lozenge setup
:revnumber: 0.2.0
:!notitle:

[CAUTION]
[.text-center]
--
Unless you want to donate your writing to the public domain,
make sure you replace the LICENSE file
with one that reflects your intent.
--

= Lozenge v{revnumber}: A tool set configuration for writing fiction.

If these sentiments ring true:

* formatting only gets in the way;
* flat files rule;
* detailed version control is a savior;
* navigation should be simple;
* scope and continuity are a pain to keep straight;
* https://sembr.org/[semantic line breaks] are useful;
* online is good, but offline is a must;

then this configuration might be for you.

[NOTE]
[.text-center]
--
Don't forget to empty out .asciidoctorconfig.adoc
and configure it by pressing kbd:[alt+a]
and follow the snippet guidance.
--

== Setup

This is a template repository
set up for writing fiction in AsciiDoc using
Visual Studio Code,
some of its extensions,
Pandoc,
and Word.

This set-up was created for MacOS
and might work out-of-the-box for Linux flavors.
For Windows machines tweaking will be required,
especially the convertAsciiDocToDocx macro
defined in `.vscode/settings.json`.

Lozenge's minimalistic approach means that
if you explore the snippets (kbd:[option|alt+s])
and the <<Keybindings>>,
you already know how most of Lozenge works.

There is one key concept and one gotcha
that might not be obvious:

. Files and document types are Lozenge's building blocks:
.. the Explorer helps managing your files and folders,
whichever way you want
.. ToDo Tree helps navigating your writing,
wherever it is stored
. PDF and DOCX files stored in (sub)folders
other than `assets/` or `published/`
are deemed generated
and will _not_ be versioned.

=== Support

Please understand,
this repository merely documents this configuration to preserve my sanity,
nothing more.

If you have questions you could open an issue.
At worst,
you will get no response.

Lozenge adheres to https://semver.org[semantic versioning].

=== Installation

These applications need to be installed:

. https://git-scm.com/download[Git] for version control;
.. if storing large, or many, binary files, install https://git-lfs.com/[GitLFS];
. https://code.visualstudio.com/Download[Visual Studio Code].
Allow it to manage your Github repository;
. extensions per the link:.vscode/extensions.json[workspace recommendations];
. https://pandoc.org/installing.html[Pandoc] to generate docx documents from AsciiDoc;
. https://www.microsoft.com/en-us/microsoft-365/mac/microsoft-365-for-mac[MS Word] for cleaning up manuscripts before they go to editors, publishers, or publishing tools;
. Optionally you can also:
.. add a https://github.com/[Github] Account for cloud backups
and ensure you have enough https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/upgrading-git-large-file-storage[LFS storage];

=== Configuration

All configuration files are well commented
or deemed self-explanatory.
link:.vscode/settings.json[settings file] is a good place to start
after finishing this document first.

==== Keybindings

From kbd:[Shift+Cmd+P],
choose `Preferences: Open Keyboard Shortcuts (JSON)`
and add the keybindings below:

[source,json]
----
[
  {
    // Run configuration snippet for .asciidoctoroconfig.adoc
    "args": {
      "name": "Configure asciidoctorconfig.adoc"
    },
    "command": "editor.action.insertSnippet",
    "key": "alt+a",
    "when": "editorTextFocus && editorLangId == asciidoc"
  },
  {
    // Save AsciiDoc as Docx
    // Saves to intermediate XML, which is hidden and deleted
    "command": "macros.convertAsciiDocToDocx",
    "key": "alt+d",
    "when": "editorFocus && editorLangId == asciidoc"
  },
  {
    // Turn Zen mode off
    "command": "macros.zenModeOff",
    "key": "alt+z",
    "when": "inZenMode"
  },
  {
    // Turn Zen mode on
    "command": "macros.zenModeOn",
    "key": "alt+z",
    "when": "!inZenMode"
  },
  {
    // Toggle showing history of modifications
    "command": "gitlens.toggleGraph",
    "key": "alt+m"
  },
  {
    // Quick access to AsciiDoc snippets
    // After the key press, type to filter
    "command": "macros.asciidocSnippets",
    "key": "alt+s",
    "when": "editorFocus && editorLangId == asciidoc"
  },
  {
    // Profiling words from current AsciiDoc file
    "command": "extension.calculateWordStats",
    "key": "alt+w",
    "when": "editorFocus && editorLangId == asciidoc"
  },
  {
    // Toggle check-box ToDos
    // Cursor must be positioned within the ToDo text
    "args": {
      "find": "((?:\\*|//)\\s+\\[)( )?(x)?(\\].*?)(?=\\n|$)",
      "isRegex": true,
      "preserveSelections": true,
      "replace": "$1${2:?x:}${3:? :}$4",
      "restrictFind": "matchAroundCursor"
    },
    "command": "findInCurrentFile",
    "key": "alt+x",
    "when": "editorTextFocus && editorLangId == asciidoc"
  },
  {
    // Workaround for "Cannot load JSON schema..." issue
    "command": "settings.cycle.vscodeIssue177142",
    "key": "alt+/",
    "when": "editorFocus && editorLangId == jsonc"
  }
]
----

==== User Settings

If things do not work as expected,
check for any user-level configurations
that could influence those set at the Workspace.
The configuration precedence is:
menu:Default[User,Workspace,User.Language,Workspace.Language].

From kbd:[Shift+Cmd+P],
choose `Preferences: Open User Settings (JSON)`
and apply the content below:

[source,json]
----
{
  "editor.fontLigatures": false, // Simplicity
  "explorer.confirmDelete": false, // Trashcan is available
  "explorer.confirmDragAndDrop": false, // Undo is available
  "grunt.autoDetect": "off",
  "gulp.autoDetect": "off",
  "jake.autoDetect": "off",
  "npm.autoDetect": "off",
  "telemetry.telemetryLevel": "off", // Privacy
  "typescript.tsc.autoDetect": "off",
  "window.autoDetectColorScheme": true, // OS-feel
  "window.nativeTabs": true, // OS-feel
  "window.titleBarStyle": "native", // Simplicity
  "workbench.colorTheme": "Kimbie Dark", // Restful
  "workbench.editor.decorations.badges": true, // Clarity
  "workbench.enableExperiments": false, // Stability
  "workbench.iconTheme": "material-icon-theme", // Descriptive icons
  "◊": true
}
----

==== Word Macros

This macro is intended to run
in newly opened Word documents
generated from a Composition AsciiDoc.

Lozenge assumes
that you keep the macro below aligned with
any changes you apply to
`lozenge/title_page.adoc`
or `lozenge/template.docx_`.

Add the below macro to the normal.dotx of your Word installation
and https://support.microsoft.com/en-us/office/customize-keyboard-shortcuts-9a92343e-a781-4d5a-92f1-0f32e3ba5b4d[assign it a keyboard shortcut]
using the category Macros.

[source]
----
Sub insertRoundedWordCount()
'
' insertRoundedWordCount Macro
' Inserts word count, rounded to the nearest thousand.
'

    Set formulaRound = Selection.Fields.Add(Range:=Selection.Range, Type:=wdFieldEmpty, Text:="=ROUND( , -3) \# #,##0", PreserveFormatting:=False)

    ' 2 characters for "{ " of the field delimiters and 7 characters for "=ROUND("
    ' The space between "(" and "," is because the countWords field will eat the space
    Set countWords = Selection.Fields.Add(Range:=formulaRound.Code.Characters(2 + 7), Type:=wdFieldEmpty, Text:="NUMWORDS", PreserveFormatting:=False)

    formulaRound.Update

End Sub

Sub deletePreamble()
'
' deletePreamble Macro
' Delete Preamble inserted by AsciiDoc/DocBook/Pandoc conversion path.
'
    ' Delete Pandoc cover page
    Application.Browser.Next
    Selection.HomeKey Unit:=wdStory, Extend:=wdExtend
    Selection.TypeBackspace

    ' Change Empty Header to Body Text
    Selection.Style = ActiveDocument.Styles("Normal")

    ' Find and format the contact information
    Selection.Find.ClearFormatting
    With Selection.Find
        .Text = ChrW(9674) & "Contact" & ChrW(9674) & "*" & ChrW(9674) & _
            "Contact" & ChrW(9674)
        .Replacement.Text = ""
        .Forward = True
        .Wrap = wdFindContinue
        .Format = False
        .MatchCase = False
        .MatchWholeWord = False
        .MatchAllWordForms = False
        .MatchSoundsLike = False
        .MatchWildcards = True
    End With
    Selection.Find.Execute
    Selection.Style = ActiveDocument.Styles("ContactInfo")

    ' Find and remove contact information markers
    Selection.HomeKey Unit:=wdStory
    Selection.Find.ClearFormatting
    Selection.Find.Replacement.ClearFormatting
    With Selection.Find
        .Text = ChrW(9674) & "Contact" & ChrW(9674)
        .Replacement.Text = ""
        .Forward = True
        .Wrap = wdFindContinue
        .Format = False
        .MatchCase = False
        .MatchWholeWord = False
        .MatchWildcards = False
        .MatchSoundsLike = False
        .MatchAllWordForms = False
    End With
    Selection.Find.Execute Replace:=wdReplaceAll

    ' Update Header
    If ActiveWindow.View.SplitSpecial <> wdPaneNone Then
        ActiveWindow.Panes(2).Close
    End If
    If ActiveWindow.ActivePane.View.Type = wdNormalView Or ActiveWindow. _
        ActivePane.View.Type = wdOutlineView Then
        ActiveWindow.ActivePane.View.Type = wdPrintView
    End If
    ActiveWindow.ActivePane.View.SeekView = wdSeekCurrentPageHeader
    ActiveWindow.ActivePane.View.NextHeaderFooter
    Selection.WholeStory
    Selection.Fields.Update
    ActiveWindow.ActivePane.View.SeekView = wdSeekMainDocument

    ' Find a replace WordCount placeholder with actual word count
    Selection.HomeKey Unit:=wdStory
    With Selection.Find
        .MatchWildcards = False
        .Text = "◊WordCount◊"
        .Execute
    End With
    Application.Run MacroName:="insertRoundedWordCount"

    'Back to top of document
    Selection.HomeKey Unit:=wdStory

    ' Save clean-up work
    ActiveDocument.Save

End Sub
----
