:Note: Lozenge setup
:revnumber: 0.0.1
:!notitle:

= Lozenge v{revnumber}: A tool set configuration for writing fiction.

[CAUTION]
[.text-center]
--
Unless you want to donate your writing to the public domain,
make sure you replace the LICENSE file
with one that reflects your intent.
--

If these sentiments ring true:

* formatting only gets in the way;
* flat files rule;
* detailed version control is a savior;
* navigation should be simple;
* scope and continuity are a pain to keep straight;
* https://sembr.org/[semantic line breaks] are useful;
* online is good, offline is a must;

then this configuration might be for you.

== Setup

This is a template repository
set up for writing fiction in AsciiDoc using
Visual Studio Code,
some of its extensions,
Pandoc,
and Word.

This set-up was created for MacOS
and might work out-of-the-box for Linux flavors.
For Windows machines tweaking will be required,
especially the convertAsciiDocToDocx macro
defined in `.vscode/settings.json`.

Lozenge's minimalistic approach means that
if you explore the snippets (kbd:[option|alt+s])
and the <<Keybindings>>,
you already know how most of Lozenge works.

There is one key concept and one gotcha
that might not be obvious:

. Files and document types are Lozenge's building blocks:
.. the Explorer helps managing your files and folders,
whichever way you want
.. ToDo Tree helps navigating your writing,
wherever it is stored
. PDF and DOCX files stored in (sub)folders
other than `assets/` or `published/`
are deemed generated
and will _not_ be versioned.

=== Support

Lozenge adheres to https://semver.org[semantic versioning].

Please understand,
this repository is merely to share my configuration,
nothing more.
If you have questions you could open an issue.
At worst,
you will get no response.

=== Installation

These applications need to be installed:

. https://git-scm.com/download[Git] for version control;
.. if storing large, or many, binary files, install https://git-lfs.com/[GitLFS];
. https://code.visualstudio.com/Download[Visual Studio Code].
Allow it to manage your Github repository;
. extensions per the link:.vscode/extensions.json[workspace recommendations];
. https://pandoc.org/installing.html[Pandoc] to generate docx documents from AsciiDoc;
. https://www.microsoft.com/en-us/microsoft-365/mac/microsoft-365-for-mac[MS Word] for sending manucripts to editors;
. Optionally you can also:
.. add a https://github.com/[Github] Account for cloud backups
and ensure you have enough https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/upgrading-git-large-file-storage[LFS storage];

=== Configuration

All configuration files are well commented
or deemed self-explanatory.
link:.vscode/settings.json[settings file] is a good place to start
after finishing this document first.

==== Keybindings

From kbd:[Shift+Cmd+P],
choose `Preferences: Open Keyboard Shortcuts (JSON)`
and add the keybindings below:

[source,json]
----
[
  {
    // Save AsciiDoc as Docx
    // Saves to intermediate XML, which is hidden and deleted
    "command": "macros.convertAsciiDocToDocx",
    "key": "alt+d",
    "when": "editorFocus && editorLangId == asciidoc"
  },
  {
    // Turn Zen mode off
    "command": "macros.zenModeOff",
    "key": "alt+f",
    "when": "inZenMode"
  },
  {
    // Turn Zen mode on
    "command": "macros.zenModeOn",
    "key": "alt+f",
    "when": "!inZenMode"
  },
  {
    // Toggle showing history of modifications
    "command": "gitlens.toggleGraph",
    "key": "alt+m",
  },
  {
    // Save AsciiDoc as default PDF export
    "command": "asciidoc.exportAsPDF",
    "key": "alt+p",
    "when": "editorFocus && editorLangId == asciidoc"
  },
  {
    // Quick access to AsciiDoc snippets
    // After the key press, type to filter
    "command": "macros.asciidocSnippets",
    "key": "alt+s",
    "when": "editorFocus && editorLangId == asciidoc"
  },
  {
    // Profiling words from current AsciiDoc file
    "command": "extension.calculateWordStats",
    "key": "alt+w",
    "when": "editorFocus && editorLangId == asciidoc"
  },
  {
    // Toggle check-box ToDos
    // Cursor must be positioned within the ToDo text
    "args": {
      "find": "((?:\\*|//)\\s+\\[)( )?(x)?(\\].*?)(?=\\n|$)",
      "isRegex": true,
      "preserveSelections": true,
      "replace": "$1${2:?x:}${3:? :}$4",
      "restrictFind": "matchAroundCursor"
    },
    "command": "findInCurrentFile",
    "key": "alt+x",
    "when": "editorTextFocus && editorLangId == asciidoc"
  },
  {
    // Workaround for "Cannot load JSON schema..." issue
    "command": "settings.cycle.vscodeIssue177142",
    "key": "alt+/",
    "when": "editorFocus && editorLangId == jsonc"
  }
]
----

==== User Settings

If things do not work as expected,
check for any user-level configurations
that could influence those set at the Workspace.
The configuration precedence is:
menu:Default[User,Workspace,User.Language,Workspace.Language].

From kbd:[Shift+Cmd+P],
choose `Preferences: Open User Settings (JSON)`
and apply the content below:

[source,json]
----
{
  "editor.fontLigatures": false, // Simplicity
  "explorer.confirmDelete": false, // Trashcan is available
  "explorer.confirmDragAndDrop": false, // Undo is available
  "grunt.autoDetect": "off",
  "gulp.autoDetect": "off",
  "jake.autoDetect": "off",
  "npm.autoDetect": "off",
  "telemetry.telemetryLevel": "off", // Privacy
  "typescript.tsc.autoDetect": "off",
  "window.autoDetectColorScheme": true, // OS-feel
  "window.nativeTabs": true, // OS-feel
  "window.titleBarStyle": "native", // Simplicity
  "workbench.colorTheme": "Kimbie Dark", // Restful
  "workbench.editor.decorations.badges": true, // Clarity
  "workbench.enableExperiments": false, // Stability
  "workbench.iconTheme": "material-icon-theme", // Descriptive icons
  "◊": true
}
----

==== Word Macros

This macro is intended to run
in newly opened Word documents
generated from a Composition AsciiDoc.

Lozenge assumes
that you keep the macro below aligned with
any changes you apply to
`lozenge/title_page.adoc`
or `lozenge/template.docx_`.

Add the below macro to the normal.dotx of your Word installation.

[source]
----
Sub insertRoundedWordCount()
'
' insertRoundedWordCount Macro
' Inserts word count, rounded to the nearest thousand.
'

    Set formulaRound = Selection.Fields.Add(Range:=Selection.Range, Type:=wdFieldEmpty, Text:="=ROUND( , -3) \# #,##0", PreserveFormatting:=False)

    ' 2 characters for "{ " of the field delimiters and 7 characters for "=ROUND("
    ' The space between "(" and "," is because the countWords field will eat the space
    Set countWords = Selection.Fields.Add(Range:=formulaRound.Code.Characters(2 + 7), Type:=wdFieldEmpty, Text:="NUMWORDS", PreserveFormatting:=False)

    formulaRound.Update

End Sub

Sub deletePreamble()
'
' deletePreamble Macro
' Undo Title page inserted by AsciiDoc/DocBook/Pandoc conversion path.
' and insert rounded word count
'
    Selection.MoveDown Unit:=wdLine, Count:=3, Extend:=wdExtend
    Selection.TypeBackspace
    Selection.Style = ActiveDocument.Styles("Normal")
    Selection.MoveDown Unit:=wdLine, Count:=1
    Selection.MoveDown Unit:=wdLine, Count:=4, Extend:=wdExtend
    Selection.Style = ActiveDocument.Styles("ContactInfo")
    Selection.MoveRight Unit:=wdCharacter, Count:=2
    Selection.EndKey Unit:=wdLine
    Selection.MoveLeft Unit:=wdCharacter, Count:=1, Extend:=wdExtend
    Application.Run MacroName:="insertRoundedWordCount"
    Selection.EndKey Unit:=wdLine
End Sub
----
